Repository saranatour1/Traval-Designer, pull requests merged in 2023-07, with the labels that each got.

#9 Sara
  README.md
  client/package.json
  client/pnpm-lock.yaml
  client/src/components/Display.jsx
  client/src/components/DisplayPosts.jsx
  client/src/components/Nav.jsx
  client/src/components/Post Components/Collab.jsx
  client/src/components/Post Components/Post.jsx
  client/src/components/Post Components/PostForm.jsx
  client/src/components/Post Components/ToDoList.jsx
  client/src/components/SearchBar.jsx
  client/src/layouts/DashBoard.jsx
  server/controllers/likes.controllers.js
  server/controllers/trip.controller.js
  server/models/trip.model.js
Labels: enhancement

#10 delete , add , edit , view a post
  README.md
  client/src/App.jsx
  client/src/components/Comments Component/Comment.jsx
  client/src/components/Comments Component/CommentDisplay.jsx
  client/src/components/Comments Component/CommentForm.jsx
  client/src/components/DisplayPosts.jsx
  client/src/components/FakeComponent.jsx
  client/src/components/Post Components/Post.jsx
  client/src/components/Post Components/PostForm.jsx
  client/src/index.css
  client/src/layouts/DashBoard.jsx
  client/src/layouts/SinglePostDetails.jsx
  client/src/layouts/Test.jsx
  server/controllers/comments.controllers.js
  server/controllers/trip.controller.js
Labels: enhancement

#11 Yousef
  client/package-lock.json
  client/package.json
  client/src/App.jsx
  client/src/components/Comments Component/Comment.jsx
  client/src/components/Comments Component/CommentDisplay.jsx
  client/src/components/Post Components/Post.jsx
  client/src/layouts/SinglePostDetails.jsx
  client/src/layouts/Test.jsx
  server/controllers/comments.controllers.js
  server/routes/comment.routes.js
Labels: enhancement

#12 Sara
  client/package.json
  client/pnpm-lock.yaml
  client/src/App.jsx
  client/src/components/DisplayPosts.jsx
  client/src/components/Profile Component/FullWidthTabs.jsx
  client/src/components/Profile Component/TabPanel.jsx
  client/src/components/Profile Component/UserCard.jsx
  client/src/layouts/UserProfile.jsx
  server/controllers/trip.controller.js
  server/controllers/user.controllers.js
  server/routes/trip.routes.js
Labels: bug

#13 Sara
  README.md
  client/src/App.jsx
  client/src/assets/github-mark-white.svg
  client/src/assets/github-mark.svg
  client/src/components/DisplayPosts.jsx
  client/src/components/NavBar Components/NavLinks.jsx
  client/src/components/NavBar Components/NotificationTab.jsx
  client/src/components/Post Components/Post.jsx
  client/src/components/Profile Component/FullWidthTabs.jsx
  client/src/components/Profile Component/UserCard.jsx
  client/src/components/TeamComponent.jsx
  client/src/layouts/SinglePostDetails.jsx
  client/src/layouts/Team.jsx
  client/src/layouts/UserProfile.jsx
  server/controllers/trip.controller.js
  server/routes/trip.routes.js
Labels: Feature

#14 Sara
  client/src/App.jsx
  client/src/components/Comments Component/Comment.jsx
  client/src/components/DisplayPosts.jsx
  client/src/components/Form Components/InputItem.jsx
  client/src/components/NavBar Components/NavLinks.jsx
  client/src/components/NavBar Components/NotificationTab.jsx
  client/src/components/Post Components/Post.jsx
  client/src/components/Post Components/PostForm.jsx
  client/src/components/Post Components/ToDoList.jsx
  client/src/components/Search Bar Components/SearchButton.jsx
  client/src/components/SearchBar.jsx
  client/src/components/SignedOutNav.jsx
  client/src/components/TeamComponent.jsx
  client/src/components/Validation Toast/Toast.jsx
  client/src/layouts/DashBoard.jsx
  client/src/layouts/MainPage.jsx
  client/src/layouts/RegestrationPage.jsx
  client/src/layouts/SignInPage.jsx
  client/src/layouts/SinglePostDetails.jsx
  client/src/layouts/Test.jsx
  client/src/layouts/UserProfile.jsx
  server/controllers/places.controllers.js
  server/controllers/user.controllers.js
Labels: enhancement

#15 Sara
  client/src/components/Post Components/PostForm.jsx
  client/src/layouts/RegestrationPage.jsx
  server/controllers/trip.controller.js
Labels: enhancement

#16 Yousef
  client/src/components/Comments Component/Comment.jsx
  client/src/components/Comments Component/CommentForm.jsx
  client/src/layouts/RegestrationPage.jsx
  client/src/layouts/SinglePostDetails.jsx
Labels: enhancement

#18 readme updates && search bar
  README.md
  client/src/components/SearchBar.jsx
  client/src/layouts/MainPage.jsx
Labels: documentation

#20 Update README.md
  README.md
Labels: documentation

#21 Sara
  README.md
  client/src/components/Comments Component/CommentForm.jsx
  client/src/layouts/SinglePostDetails.jsx
  client/src/layouts/Team.jsx
  client/src/layouts/UserProfile.jsx
Labels: enhancement

#22 Sara
  client/public/vite.svg
  client/src/components/Display.jsx
  client/src/components/FakeComponent.jsx
  client/src/components/Post Components/Collab.jsx
  client/src/components/Post Components/PostForm.jsx
  client/src/components/Post Components/ToDoList.jsx
  client/src/components/Profile Component/FullWidthTabs.jsx
  client/src/components/SearchBar.jsx
  client/src/layouts/MainPage.jsx
  client/src/layouts/RegestrationPage.jsx
  client/src/layouts/Team.jsx
  server/controllers/places.controllers.js
  server/routes/trip.routes.js
Labels: enhancement, Feature

#24 custom hooks - use coordinates + nearby
  client/src/hooks/useCoordinates.jsx
  client/src/hooks/useNearby.jsx
  client/src/layouts/MainPage.jsx
Labels: enhancement

#25 added images capture to the display
  client/src/components/Display.jsx
  client/src/components/SearchBar.jsx
  client/src/hooks/useCoordinates.jsx
  client/src/hooks/useNearby.jsx
  client/src/layouts/MainPage.jsx
Labels: enhancement

#26 small fix to get the object id instead of index, small issue with rep…
  client/src/components/Display.jsx
Labels: enhancement

#27 Sara
  client/src/components/SearchBar.jsx
  client/src/components/Validation Toast/Toast.jsx
  client/src/hooks/useErrors.jsx
  client/src/hooks/useErrors2.jsx
  client/src/hooks/usePosts.jsx
  client/src/layouts/DashBoard.jsx
  client/src/layouts/RegestrationPage.jsx
  client/src/layouts/SignInPage.jsx
  server/controllers/user.controllers.js
Labels: enhancement

#28 Sara
  .vscode/settings.json
  client/src/components/Display.jsx
  client/src/components/DisplayPosts.jsx
  client/src/components/Post Components/PostForm.jsx
  client/src/layouts/DashBoard.jsx
Labels: enhancement

#29 Sara
  client/src/components/DisplayPosts.jsx
  client/src/components/Post Components/Post.jsx
  client/src/hooks/useDateTime.jsx
  client/src/hooks/useLoggedUser.jsx
  client/src/hooks/usePost.jsx
  client/src/layouts/SignInPage.jsx
  client/src/layouts/SinglePostDetails.jsx
  server/controllers/user.controllers.js
Labels: documentation, enhancement

#30 I broke it lol
  README.md
  client/package.json
  client/pnpm-lock.yaml
  client/src/components/Comments Component/Comment.jsx
  client/src/components/Comments Component/CommentDisplay.jsx
  client/src/components/Comments Component/CommentForm.jsx
  client/src/components/Post Components/Collab.jsx
  client/src/components/Post Components/Post.jsx
  client/src/components/Post Components/PostForm.jsx
  client/src/components/Post Components/ToDoList.jsx
  client/src/hooks/useDateTime.jsx
  client/src/hooks/useLoggedUser.jsx
  client/src/hooks/usePost.jsx
  client/src/layouts/SinglePostDetails.jsx
  server/controllers/comments.controllers.js
Labels: bug

#32 Removed consolelogs , updated trip content maximum length
  client/src/App.jsx
  client/src/components/Comments Component/Comment.jsx
  client/src/components/Comments Component/CommentForm.jsx
  client/src/components/Nav.jsx
  client/src/components/Post Components/Post.jsx
  client/src/components/Post Components/PostForm.jsx
  client/src/components/Profile Component/UserCard.jsx
  client/src/layouts/MainPage.jsx
  client/src/layouts/RegestrationPage.jsx
  client/src/layouts/SignInPage.jsx
  client/src/layouts/SinglePostDetails.jsx
  client/src/layouts/Test.jsx
  client/src/layouts/UserProfile.jsx
  server/models/trip.model.js
Labels: enhancement
